### ISSUE TITLE
Zen Mode Darmanitan

### ISSUE THREAD

**Issue by CodeMonkey90** [itsjavi/supereffective-dataset#13]
In the HOME dex, Zen Mode Darmanitan and Galarian Zen Mode Darmanitan are not tracked separately, even though they are connected to a distinct form. Considering both Battle Bond Greninja and Own Tempo Rockruff have their own entries, this seems strange and inconsistent.

**Comment by itsjavi** [comment]
they are considered separate forms with special abilities that cannot be changed with ability patch

**Comment by CodeMonkey90** [comment]
OK, that argument makes sense. But does the Zen Mode form register in the HOME pokedex if you have never encountered that form before and only deposit a "regular" Darmanitan? If not, then I think the hidden ability would at least be worth mentioning, as the living dex + forms would not be complete otherwise.
