### ISSUE TITLE
Break regions into new boxes

### ISSUE THREAD

**Issue by Pacha56** [itsjavi/supereffective-dataset#8]
Hey

Do you think you could add an option to start each region in a new box?

Thanks

**Comment by itsjavi** [comment]
that's already an option for the HOME dex tracker. "Grouped by Regions"

**Comment by Pacha56** [comment]
Sorry I didn't explain correctly. Probably a bit weird but I like it grouped by region and sorted by forms combined

**Comment by itsjavi** [comment]
Sorry but that's not currently in our plans. All sorting options are only orientative, each trainer can sort their real boxes however they want.
